use_frameworks!

platform :ios, '9.0'

target 'Vega_Example' do
  pod 'SweetSugar', :path => '../../SweetSugar'
  pod 'Vega', :path => '../'

  target 'Vega_Tests' do
    inherit! :search_paths

    
  end
end
