use_frameworks!

platform :ios, '9.0'

target 'Vega_Example' do
  pod 'Vega', :path => '../'
  pod 'SweetSugar', :git => 'https://github.com/alexwind-lin/SweetSugar.git'

  target 'Vega_Tests' do
    inherit! :search_paths

    
  end
end
